spring:
  profiles:
    active: local

pebble:
  suffix: .html
  cache: false

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://10.30.175.15:3306/jmlim_chat?allowPublicKeyRetrieval=true&useSSL=false
    username: jmlim
    password: password
    driver-class-name: com.mysql.jdbc.Driver

