spring:
  profiles:
    active: local

pebble:
  suffix: .html
  cache: false

## 로깅 레벨 추가
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    ## security 로그 보기 위해 설정
    org.springframework.security: debug
    io.jmlim.chat: debug

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://10.30.175.15:3306/jmlim_chat?allowPublicKeyRetrieval=true&useSSL=false
    username: jmlim
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

